### ISSUE TITLE
Setup scaffolding for new standalone search page site

### ISSUE THREAD

**Issue by CathyJinJNCC** [jncc/jncc-website-search#5]
We've decided we want to spin out the search page into its own separate app. We're thinking of using lambda (cheap and suited to the task) but are concerned about the delays from a cold start. Need to investigate how long the delays are, if any, and whether that's acceptable.

- [x] Investigate lambda cold start delays - total response time to browser (returning JSON results of a simple search request) is ~0.5 seconds for hot start and ~1-1.5 seconds for cold start. Ulli and Jon have agreed a delay on the first request of 1-2 seconds is acceptable.
- [x] Create skeleton app, e.g. terraform config for http api gateway + lambda function that returns hello world page (use node for faster cold start times)
- [x] Investigate and setup basic error handling pages (404/500) - split out into dev#354
- [x] Setup rate limiting/throttling (10/10?) on api requests and reserve capacity (1?) on lambda to manage our costs  - ip based rate limiting done as part of dev#353
- [x] Setup monitoring/alerting on gateway requests - lambda alerting done as part of dev#359

**Comment by CathyJinJNCC** [comment]
Something to consider - automating the set up of elasticsearch index mappings (e.g. for alphabetical sorting on the search page we need the title field to be sortable, which means updating the doc mappings to add it as a "keyword" type as well as a "text" type). Most likely out of scope for this task but worth thinking about.
